### ISSUE TITLE
Set development mode for webpack-dev-server

### ISSUE THREAD

**Issue by filleokus** [mkontogiannis/p5.js-es6-boilerplate#3]
Great little starter repo, thanks!

I noticed that the performance was unexpectedly slow when running the development server. Apparently, `webpack-dev-server` does not set the `mode` variable to something sane (development...) per default (https://github.com/webpack/webpack-dev-server/issues/1327). This causes `uglifyjs` to be run on every change, which is quite slow due to the large size of `p5`.

There are probably more elegant ways to fix this, but I just changed the command with which `webpack-dev-server` is started in `package.json` like this:
```
    "dev": "webpack-dev-server --mode development --progress --colors --inline --hot --open",
```

This increased the speed of the hot-reload quite dramatically for me!

Thanks again for sharing this

**Comment by mkontogiannis** [comment]
Hi thanks a lot for reporting this and apologies for the really late response, this should be fixed with an update to the latest `webpack-dev-server`. I hope you have been enjoying this boilerplate and have created some cool sketches!
